### PR TITLE
change pull to rebase

### PR DESCRIPTION
**Pull request by rabernat**
I suggest recommending `rebase` (rather than `pull` i.e. `merge`) for updating a local fork.

Some discussions of the pros and cons of each:
https://www.atlassian.com/git/tutorials/merging-vs-rebasing
https://blog.sourcetreeapp.com/2012/08/21/merge-or-rebase/

### CODE REVIEW

**Comment by jahn** [comment]
I thought it was assumed that master is never changed from upstream.  In this case bringing up rebase of master is kind of confusing.  I would rebase my topical branch, but for master basically pull --ff-only and start worrying if it's not a fast forward.

**Comment by rabernat** [comment]
Fair point...if people follow the rules of never committing to their local master, I guess it wouldn't make any difference.

**Comment by rabernat** [comment]
Some big open source projects seem to recommend rebase:
https://docs.scipy.org/doc/numpy/dev/gitwash/following_latest.html#updating-the-code

While others recommend merge:
https://pandas.pydata.org/pandas-docs/stable/contributing.html#delete-your-merged-branch-optional

**Comment by edoddridge** [comment]
@rabernat, did you mean to link to this page?
 https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#development-workflow

My main concern with `rebase`, is that many members of the developer community for MITgcm are unfamiliar with `git`, and it only takes a small accident with `rebase` to really screw things up. Merge commits can at least be reverted if something went wrong. 

Essentially, I was trying to make the workflow as robust as possible to stop people getting frustrated with `git` before they'v had a chance to get familiar with it.

**Comment by rabernat** [comment]
Sure, agreed.

**Pull request closed without merging**
