### PR TITLE
Sphinx based documentation

### PR DESCRIPTION
**Pull request by edoddridge**
This PR represents the beginning of the process of porting the documentation from LaTeX to Sphinx, and building and hosting that documentation on Read The Docs. (Due to my experimentation with readthedocs.org, there may be a name clash when rtd.org tries to build the docs for this repo - we'll have to sort that out if errors ensue.)

This PR is intended to provide the skeleton upon which others may experiment with this format for the documentation; it does **not** represent a complete version of the documentation.

Changes:
 - The original `docs` folder has been moved to `developer_docs`
 - A new folder called `docs` has been created
 - Some text and figures from the current manual have been ported to this new format. This process is by no means complete, but provides examples of:
   - figures
   - equations
   - animated gifs in the html output
   - labelled and cross-referencable chapters, sections, subsections, and paragraphs
   - citations
   - inclusion of configuration files from the verification experiments
 - Configuration files for building the documentation, either locally or on readthedocs.org
 - Guidelines for formatting contributions to the manual
 - Guidelines for contributing to the repo

### CODE REVIEW

**Comment by jm-c** [comment]
I am concerned about the first change, i.e., renaming doc folger to developer_docs:
${ROOTDIR}/doc/tag-index is currently used by genmake2 and, although this could be changed,
i think it would be preferable to leave genamke2 unchanged for a smooth transition from cvs to git. This 
way users could use the same genmake2 in both the cvs downloaded version and the git version.

**Comment by edoddridge** [comment]
OK, that's a pretty serious problem. I agree it's better to keep `genmake2` consistent between cvs and git versions of the code.

I see two main options going forward, either:
- start a new pull request moving it back; or
- leave it be in this test repository, but vow not to make the same mistake when we do the real one.

There is a third option to revert the commit that renames the folder and rewrite the history, but it will cause *lots* of trouble for everyone who has forked the repository. I don't think that's a good idea.

**Comment by jm-c** [comment]
Hi Ed,

I would vote for solution #2, it's simpler and as long as we keep in mind it's not 
how the real one should be, it's ok.

Cheers,
Jean-Michel

**Comment by edoddridge** [comment]
OK, sounds good.

**Pull request merged**
