### PR TITLE
test local latex macros

### PR DESCRIPTION
**Pull request by jahn**
Latex macros can be defined locally in a file, provided they are in a math environment.
The definition is at the end of the first paragraph, so it doesn't introduce an empty line.  Could have added a backslash-space at the end of the line and placed it above the paragraph, but that seems like a bad thing to do.

### CODE REVIEW

**Comment by christophernhill** [comment]
@jahn this looks good to me.

Chris

**Comment by edoddridge** [comment]
Neat! 

Is it possible to put the macro definitions in a separate file and `include` them? Somewhat like [this](https://stackoverflow.com/a/2472605)? That way they could be defined once and used everywhere in the documentation.

**Comment by jahn** [comment]
Aha!  But now it introduces a vertical space as I can no longer tack it onto a paragraph.  The backslash-space trick inside the include file doesn't help either.  Any ideas?

It also shows a huge block of tex at the top of the page for a moment...

**Comment by edoddridge** [comment]
I tried playing around with this and couldn't find a way to use a separate definitions file that didn't result in additional whitespace. It seems like there are solutions for [html output](https://stackoverflow.com/a/19268549), but none that work for both latexpdf and html. Perhaps we're simply trying to be too clever. 

Placing the macro definition in the first equation seems like a pretty ok solution to me. Using this code:
 
```
.. math::

   \newcommand{\pp}[2]{\frac{\partial #1}{\partial #2}}
   \pp{\eta(z)}{z} = \lambda \hspace{0.4cm}or\hspace{0.4cm} \pp{\eta(P^{\kappa})}{P^{\kappa}} = 
   -\frac{c_p}{g}\theta\lambda
```

I don't get any additional whitespace, or obvious tex garbage as the page loads (the additional commands are there, but aren't obvious when next to the equation).

I'm not sure that this is any better than your initial fix of putting it at the end of the first paragraph.

**Comment by christophernhill** [comment]
@jahn any more thoughts on this. It seems like the original form was best for now i.e. paste all macros at end of first paragraph.

**Comment by edoddridge** [comment]
I agree with @christophernhill - the original method of placing the macro definitions at the end of the first paragraph seems like the best solution.

Is there anything else that needs to be addressed before this gets merged?

**Comment by jahn** [comment]
This does not actually work for the latex build.  For this, one has to include the definitions in the preamble in latex_elements in conf.py.  This means latex macros will be global, but MathJax ones not, which is kind of annoying.  One also has to hide the local definitions from latex using an "only" directive which means they have to be a paragraph by themselves, most likely best placed at the very top of the file where extra vertical space is not as much of a bother.  I'd suggest trying to get rid of macros for now, except maybe in the one case where they are heavily used (nonlin_visc).  We could look into getting the global MathJax thing that Ed referenced to work and then have a set of global macros.  It seems that this is not easily achievable on readthedocs.org right now, though.

**Comment by jahn** [comment]
This should work, except for the undesired space (and temporary MathJax code) at the top of the html page.  With the html-only include file and the latex preamble, macros need to be defined in only two places and can be used globally (by including the defs.hrst file).

**Pull request closed without merging**
